import type { Metadata } from "next";
import { DM_Sans } from "next/font/google";
import "./globals.css";
import { AllProviders } from "@/contexts";
import { Button } from "@/components/ui";
import AppHeader from "@/components/ui/app-header";

const DMSans = DM_Sans({
  variable: "--font-sans",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <AllProviders>
        <body
          className={`${DMSans.className} antialiased`}
          style={{
            background: `url('/app-bg.png')`,
            backgroundSize: "cover",
            backgroundPosition: "center",
            backgroundRepeat: "no-repeat",
          }}
        >
          <div className="relative h-screen overflow-hidden">
            <AppHeader />
            <main className="!h-[calc(100vh-80px)] md:!h-[calc(100vh-100px)] overflow-y-auto">
              {children}
            </main>
          </div>
        </body>
      </AllProviders>
    </html>
  );
}
